# Generated by Django 4.0.3 on 2022-04-07 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoCog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('cuidador', models.ManyToManyField(blank=True, default='', related_name='cuidadores', to='diario.cuidador')),
                ('grupoCog', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='participante', to='diario.grupocog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('grupoCare', models.ManyToManyField(blank=True, related_name='mentores', to='diario.grupocare')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoAvalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.avaliador')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facilitador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('grupoCog', models.ManyToManyField(blank=True, related_name='facilitadores', to='diario.grupocog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cuidador',
            name='grupoCare',
            field=models.ManyToManyField(blank=True, related_name='cuidadores', to='diario.grupocare'),
        ),
    ]
