# Generated by Django 4.0.3 on 2022-04-19 10:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('data_anscimento', models.DateField(blank=True, null=True)),
                ('local_nascimento', models.CharField(blank=True, max_length=20, null=True)),
                ('diagnostico', models.CharField(blank=True, max_length=20, null=True)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participante', to='diario.grupo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1000)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=1000)),
                ('data', models.DateTimeField(default=datetime.datetime(2022, 4, 19, 11, 49, 40, 874706))),
                ('sessao', models.CharField(default='1', max_length=10, null=True)),
                ('grupo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diario.grupo')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
            ],
        ),
        migrations.CreateModel(
            name='Dinamizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('grupo', models.ManyToManyField(related_name='dinamizadores', to='diario.grupo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
