# Generated by Django 4.0.3 on 2022-04-19 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 11, 50, 19, 838872)),
        ),
    ]
