# Generated by Django 4.0.3 on 2022-04-19 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_alter_nota_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.grupo'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='sessao',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
