# Generated by Django 4.0.3 on 2022-04-20 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0004_sessao_alter_participante_grupocog_nota_exercicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partilha', models.TextField()),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
            ],
        ),
    ]
