# Generated by Django 4.0.3 on 2022-04-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0005_partilha'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='data',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='partilha',
            name='data',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
