# Generated by Django 4.0.3 on 2022-04-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0006_nota_data_partilha_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliar',
            name='grupoCog',
            field=models.ManyToManyField(blank=True, related_name='auxiliares', to='diario.grupocog'),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='grupoCare',
            field=models.ManyToManyField(blank=True, related_name='cuidadores', to='diario.grupocare'),
        ),
        migrations.AlterField(
            model_name='dinamizadorconvidado',
            name='grupoCare',
            field=models.ManyToManyField(blank=True, related_name='dinamizadores', to='diario.grupocare'),
        ),
        migrations.AlterField(
            model_name='facilitador',
            name='grupoCog',
            field=models.ManyToManyField(blank=True, related_name='facilitadores', to='diario.grupocog'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='grupoCare',
            field=models.ManyToManyField(blank=True, related_name='mentores', to='diario.grupocare'),
        ),
    ]
