# Generated by Django 4.0.3 on 2022-05-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0010_presenca_partilhagrupo_notagrupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='mode',
            field=models.CharField(blank=True, choices=[('P', 'Presencial'), ('O', 'Online')], default='P', max_length=20, null=True),
        ),
    ]
