# Generated by Django 4.0.3 on 2022-05-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0011_alter_presenca_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='nota',
            field=models.TextField(default=''),
        ),
    ]
