# Generated by Django 4.0.3 on 2022-06-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0012_presenca_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='faltou',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
