# Generated by Django 4.0.3 on 2022-06-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0015_alter_presenca_faltou'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='present',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='faltou',
            field=models.BooleanField(default=True),
        ),
    ]
