# Generated by Django 4.0.3 on 2022-06-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0018_rename_nota_notagrupo_notag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='notaG',
            field=models.TextField(),
        ),
    ]
