# Generated by Django 4.0.3 on 2022-06-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0020_alter_presenca_notag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notagrupo',
            old_name='notaG',
            new_name='nota',
        ),
    ]
