# Generated by Django 4.0.3 on 2022-06-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0021_rename_notag_notagrupo_nota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notagrupo',
            old_name='nota',
            new_name='notaG',
        ),
    ]
