# Generated by Django 4.0.3 on 2022-06-13 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0022_rename_nota_notagrupo_notag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notagrupo',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.grupocare'),
        ),
    ]
