# Generated by Django 4.0.3 on 2022-06-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0023_alter_notagrupo_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='tipoSessao',
            field=models.CharField(blank=True, choices=[('PR', 'Protocolo'), ('CG', 'Cog'), ('CR', 'Care')], default='CR', max_length=20, null=True),
        ),
    ]
