# Generated by Django 4.0.3 on 2022-06-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0024_presenca_tiposessao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='notaG',
            field=models.TextField(blank=True, null=True),
        ),
    ]
