# Generated by Django 4.0.3 on 2022-06-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0025_alter_presenca_notag'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostas',
            name='pergunta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
