# Generated by Django 4.0.3 on 2022-06-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0026_respostas_pergunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostas',
            name='pergunta',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
