# Generated by Django 4.0.3 on 2022-07-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0028_informacoesgrupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacoesgrupo',
            old_name='informacoesGrupo',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='notagrupo',
            old_name='notaG',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='partilhagrupo',
            old_name='partilha',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='presenca',
            old_name='notaG',
            new_name='descricao',
        ),
    ]
