# Generated by Django 4.0.3 on 2022-07-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0029_rename_informacoesgrupo_informacoesgrupo_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
