# Generated by Django 4.0.3 on 2022-07-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0030_alter_exercicio_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='sessao',
            field=models.ManyToManyField(related_name='exercicios', to='diario.sessao'),
        ),
    ]
