# Generated by Django 4.0.3 on 2022-07-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0035_exercicio_dinamizadores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercicio',
            old_name='sessao',
            new_name='sessoes',
        ),
    ]
