# Generated by Django 4.0.3 on 2022-07-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0037_exercicio_atividade_exercicio_componentes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='componentes',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='dinamizadores',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='instrucao',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='introducao',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='objetivo',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='sessoes',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='tema',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='sessao',
            field=models.ManyToManyField(related_name='exercicios', to='diario.sessao'),
        ),
    ]
