# Generated by Django 4.0.3 on 2022-07-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0040_exercicio_atividade_exercicio_objetivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='instrucoes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='introducao',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
