# Generated by Django 4.0.3 on 2022-07-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0041_alter_sessao_instrucoes_alter_sessao_introducao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='atividade',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='objetivo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
