# Generated by Django 4.0.3 on 2022-07-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0047_rename_nota_notagrupo_notagrupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='estado',
            field=models.CharField(blank=True, choices=[('PR', 'Por realizar'), ('R', 'Realizado')], default='PR', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sessao',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='sessoes', to='diario.grupocare'),
        ),
        migrations.AddField(
            model_name='sessao',
            name='numeroSessao',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sessao',
            name='regime',
            field=models.CharField(blank=True, choices=[('P', 'Presencial'), ('O', 'Online'), ('M', 'Misto')], default='P', max_length=20, null=True),
        ),
    ]
