# Generated by Django 4.0.3 on 2022-07-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0048_sessao_estado_sessao_numerosessao_sessao_regime'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='grupo',
            field=models.ManyToManyField(blank=True, related_name='gruposessao', to='diario.grupocare'),
        ),
    ]
