# Generated by Django 4.0.3 on 2022-07-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0048_sessao_estado_sessao_grupos_sessao_numerosessao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='sessaoGrupo',
            field=models.ManyToManyField(blank=True, related_name='sessaodogrupo', to='diario.grupocare'),
        ),
    ]
