# Generated by Django 4.0.3 on 2022-07-16 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0048_sessao_estado_sessao_numerosessao_sessao_regime'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='grupoCog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessaodogrupo', to='diario.grupocog'),
        ),
    ]
